name: Linux Build

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/linux.yml"
      - "src/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/linux.yml"
      - "src/**"
      - "CMakeLists.txt"

jobs:
  build:
    name: ${{matrix.cxx}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-12
          - clang++-15
        include:
          - cxx: g++-12
            compiler: g++-12
          - cxx: clang++-15
            compiler: clang++-15
    env:
      CXX: ${{matrix.cxx}}
      CMAKE_PREFIX_PATH: ${{github.workspace}}/.local
    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja
      run: sudo apt install ninja-build clang-15 -y
       
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

